################################### Default Configuration ############################
baseURL = "/"
languageCode = "en-us"
title = "ITG | International Trade Group"
#theme = "agen-hugo"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/card-slider/css/style.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  URL = "plugins/counto/apear.js"
  [[params.plugins.js]]
  URL = "plugins/counto/counTo.js"
  [[params.plugins.js]]
  URL = "plugins/card-slider/js/card-slider-min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


###################################### Navigation ######################################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Cases"
  URL = "cases"
  weight = 3
  
  [[menu.main]]
  name = "Product"
  URL = "products"
  weight = 4

  [[menu.main]]
  name = "Other"
  weight = 5
  hasChildren = true

    [[menu.main]]
    parent = "Other"
    name = "Team"
    URL = "team"
    
    [[menu.main]]
    parent = "Other"
    name = "Blog"
    URL = "blog"
    
    [[menu.main]]
    parent = "Other"
    name = "FAQs"
    URL = "faqs"

  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6

  ############################# Footer menu ################################
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.footer]]
  name = "Cases"
  URL = "cases"
  weight = 3
  
  [[menu.footer]]
  name = "Product"
  URL = "products"
  weight = 4
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5



########################### Default parameters ##########################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Anastasiia Berest"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "50.4405345"
mapLongitude = "30.5389159"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  ############################# Footer Start ###########################

  # footer about
  [params.footer.about]
  about = "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, odit? Sapiente et temporibus qui corporis veritatis ipsa culpa, numquam id."

  # contact form
  [params.form]
  formAction = "#"

  # copyright
  [params.copyright]
  copyright = "Copyright &copy;2022"

  ######################### Social site ##############################
  [[params.social]]
  icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  icon = "ti-github" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  icon = "ti-instagram" # themify icon pack https://themify.me/themify-icons
  link = "#"