baseURL = "/"
canonifyURLs = false
defaultContentLanguage = "ru"
disableLanguages = []
languageCode = "ua"
paginate = "6"
relativeURLs = true
summaryLength = "50"
title = "ITG | International Trade Group"
# [Languages.en]
# contentDir = "content/en"
# home = "Home"
# languageCode = "en-us"
# languageName = "En"
# weight = 3
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2
[Languages.ua]
contentDir = "content/ua"
home = "Головна"
languageCode = "ua"
languageName = "Укр"
weight = 1

[[menu.header]]
URL = "#how-work"
name = "Как работает?"
weight = 1
hasChildren = true

[[menu.header]]
URL = "#features"
name = "Особенности"
weight = 2
hasChildren = true

[[menu.header]]
URL = "#stat"
name = "Статистика"
weight = 3
hasChildren = true

[[menu.header]]
URL = "#testimonials"
name = "Подписки"
weight = 4
hasChildren = true

[[menu.header]]
URL = "#contacts"
name = "Контакты"
weight = 5
hasChildren = true

[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
CIO_site_id = "XXX"
GTM = "GTM-XXX"

description = ""
develop = "xfr"
home = "Home"

logo = "/images/logo.png"
logo_w = "161"
logo_h = "84"
copyright = "All Rights Reserved 2022 ITG"

tm_id = "-587397444"
tm_token = "2045157225:AAFQjtb_C69OrQqaXjNLnpODfFy01tIe1Lg"

[[params.plugins.js]]
link = "plugins/js/bootstrap.bundle.min.js"
[[params.plugins.js]]
link = "plugins/js/jquery.min.js"
[[params.plugins.js]]
link = "plugins/js/parallax.min.js"


[[params.soc]]
title = "tiktok"
icon = "tiktok" 
icon_h = "tiktok2" 
link = "https://www.tiktok.com/@itg_general__"

[[params.soc]]
title = "instagram"
icon = "im" 
icon_h = "im2"
link = "https://instagram.com/itg_official__"

[[params.soc]]
title = "telegram"
icon = "tm" 
icon_h = "tm2"
link = "https://t.me/ITG_club"

[[params.soc]]
title = "linkedin"
icon = "in" 
icon_h = "in2"
link = "https://www.linkedin.com/in/international-trade-group"

[[params.soc]]
title = "youtube"
icon = "ytb" 
icon_h = "ytb2"
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"

[[params.soc]]
title = "site"
icon = "site" 
icon_h = "site2"
link = "https://itg-investments.com/"

[params.preloader]
enable = true
preloader = ""
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

